# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Machine_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_time', models.IntegerField(default=0)),
                ('total_rules', models.IntegerField(default=0)),
                ('machine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphgen.Machine')),
            ],
        ),
    ]
