# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphgen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_data',
            name='machine_name',
        ),
        migrations.AddField(
            model_name='machine',
            name='bucket_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='total_rules',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Machine_Data',
        ),
    ]
