# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphgen', '0002_auto_20160906_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_dfw1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_time', models.IntegerField(default=0)),
                ('total_rules', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Machine_iad1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_time', models.IntegerField(default=0)),
                ('total_rules', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Machine_sjc1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_time', models.IntegerField(default=0)),
                ('total_rules', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(max_length=20),
        ),
    ]
