# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graphgen', '0003_auto_20160907_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_dfw1',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine_iad1',
            name='user_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine_sjc1',
            name='user_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
